# Generated by Django 4.2.5 on 2023-09-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='disciplines',
        ),
        migrations.CreateModel(
            name='TarefasDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('Tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarefa')),
            ],
        ),
    ]
