# Generated by Django 4.2.5 on 2023-09-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tarefa_disciplines_tarefasdisciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='disciplinas',
            field=models.ManyToManyField(to='api.disciplina'),
        ),
    ]
