# Generated by Django 4.2.5 on 2023-09-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tarefa_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='aluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='tarefas',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tarefa'),
            preserve_default=False,
        ),
    ]
