# Generated by Django 4.2.5 on 2023-09-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_aluno_tarefas_tarefa_aluno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disciplina',
            new_name='Discipline',
        ),
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='TarefasDisciplinas',
            new_name='TasksDisciplines',
        ),
    ]
