# Generated by Django 4.2.5 on 2023-09-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_disciplina_discipline_rename_aluno_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='disciplinas',
            new_name='discipline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='aluno',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='tasksdisciplines',
            old_name='Disciplina',
            new_name='disciplines',
        ),
        migrations.RenameField(
            model_name='tasksdisciplines',
            old_name='Tarefa',
            new_name='tasks',
        ),
    ]
