# Generated by Django 4.2.5 on 2023-09-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_disciplinas_task_discipline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasksDisciplines',
        ),
    ]
